<?php
/**
 * Blackboard CLI Apps Configuration File.
 *
 * This file will be automatically loaded by the command line application.
 *
 * @package    BlackboardCli
 *
 * @copyright  Copyright (C) 2012 Omar E. Ramos, Imperial Valley College. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 */

// Prevent direct access to this file outside of a calling application.
defined('_JEXEC') or die;

/**
 * CLI configuration class.
 *
 * @package  BlackboardCli
 * @since    11.3
 */
final class JConfig
{
	/**
	 * The database driver.
	 *
	 * @var    string
	 * @since  11.3
	 */
	public $dbDriver = 'mysqli';

	/**
	 * Database host.
	 *
	 * @var    string
	 * @since  11.3
	 */
	public $dbHost = 'localhost';

	/**
	 * The database connection user.
	 *
	 * @var    string
	 * @since  11.3
	 */
	public $dbUser = 'root';

	/**
	 * The database connection password.
	 *
	 * @var    string
	 * @since  11.3
	 */
	public $dbPass = '';

	/**
	 * The database name.
	 *
	 * @var    string
	 * @since  11.3
	 */
	public $dbName = '';

	/**
	 * The database table prefix, if necessary.
	 *
	 * @var    string
	 * @since  11.3
	 */
	public $dbPrefix = '';

	/**
	 * A valid PHP Timezone Value
	 * Refer to the PHP Timezones Link
	 * below for valid string values.
	 *
	 * @link http://php.net/manual/en/timezones.php
	 * @var string
	 */
	public $timezone = 'America/Los_Angeles';

	/**
	 * Configuration option to show
	 * the SPRIDEN_ID values in the generated
	 * log file.
	 *
	 * @var bool
	 */
	public $includeSpridenIdsInLog = false;

	/**
	 * Used in the terms, course category,
	 * and course category membership sync
	 * processes.
	 *
	 * It is the number of days to continue
	 * showing the data for the last term
	 * before disabling it.
	 *
	 * @var int
	 */
	public $daysToContinueShowing = 45;

	/**
	 * Oracle Host
	 *
	 * @var string
	 */
	public $oracleHost = '';

	/**
	 * Oracle Username
	 *
	 * @var string
	 */
	public $oracleUsername = '';

	/**
	 * Oracle Password
	 *
	 * @var string
	 */
	public $oraclePassword = '';

	/**
	 * Oracle Service Name
	 *
	 * @var string
	 */
	public $oracleServiceName = '';

	/**
	 * Oracle Port
	 *
	 * @var string
	 */
	public $oraclePort = '1521';

	/**
	 * Person - New Data Source Key.
	 *
	 * @var string
	 */
	public $personDataSourceKey = '';

	/**
	 * Employee Email Domain to
	 * be used in the Person Sync App.
	 *
	 * For our campus we are only filling out
	 * the GOBTPAC_LDAP_USER database field for
	 * our staff users so that's where employee usernames
	 * are coming from. These usernames are then combined
	 * with the employee email domain to create their
	 * email address.
	 *
	 * @var string
	 */
	public $employeeEmailDomain = 'example.com';

	/**
	 * Student Email Domain to
	 * be used in the Person Sync App.
	 *
	 * For our campus we are creating student
	 * email accounts using the default username
	 * generated by Banner in the GOBTPAC_EXTERNAL_USER
	 * database field. This is combined with the
	 * student email domain below to create the student
	 * email address.
	 *
	 * @var string
	 */
	public $studentEmailDomain = 'students.example.com';

	/**
	 * Blackboard Field Separator to use
	 * when Generating Files:
	 *
	 * @var string
	 */
	public $blackboardFieldSeparator = '|';

	/**
	 * The Blackboard Submission Mode
	 * Use 'test' to use the test domain
	 * and 'production' to use the production domain
	 *
	 * @var string
	 */
	public $blackboardMode = 'test';

	/**
	 * The Blackboard Production Domain
	 *
	 * @var string
	 */
	public $blackboardDomain = 'example.blackboard.com';

	/**
	 * The Blackboard Test Domain
	 *
	 * @var string
	 */
	public $blackboardTestDomain = 'exampletest.blackboard.com';

	/**
	 * Course Username/Password Section:
	 *
	 * @var string
	 */
	public $courseServiceUsername = '';
    public $courseServicePassword = '';
	public $courseServiceTestUsername = '';
    public $courseServiceTestPassword = '';

    /**
	 * Course Membership Username/Password Section:
	 *
	 * @var string
	 */
	public $courseMembershipServiceUsername = '';
    public $courseMembershipServicePassword = '';
	public $courseMembershipServiceTestUsername = '';
    public $courseMembershipServiceTestPassword = '';

    /**
	 * Course Category Username/Password Section:
	 *
	 * @var string
	 */
	public $courseCategoryServiceUsername = '';
    public $courseCategoryServicePassword = '';
	public $courseCategoryServiceTestUsername = '';
    public $courseCategoryServiceTestPassword = '';

    /**
	 * Course Category Membership Username/Password Section:
	 *
	 * @var string
	 */
	public $courseCategoryMembershipServiceUsername = '';
    public $courseCategoryMembershipServicePassword = '';
	public $courseCategoryMembershipServiceTestUsername = '';
    public $courseCategoryMembershipServiceTestPassword = '';

    /**
	 * Person Username/Password Section:
	 *
	 * @var string
	 */
	public $personServiceUsername = '';
    public $personServicePassword = '';
	public $personServiceTestUsername = '';
    public $personServiceTestPassword = '';

    /**
	 * Term Username/Password Section:
	 *
	 * @var string
	 */
	public $termServiceUsername = '';
    public $termServicePassword = '';
	public $termServiceTestUsername = '';
    public $termServiceTestPassword = '';

    /**
    * Email Notification Information Section:
    */

    /**
    * From Email for Notifications
    *
    * @var string
    */
	public $notificationFromEmail = 'test@example.com';

	/**
    * From Name for Notifications
    *
    * @var string
    */
	public $notificationFromName = 'John Doe';

	/**
    * To Email(s) for Notifications
    *
    * Just separate multiple email address by commas
    *
    * @var string
    */
	public $notificationToEmail = 'test@example.com';

	/**
	 * SMTP Information Section:
	 */

	/**
	 * Enable using SMTP when sending out
	 * the email notifications.
	 *
	 * @var bool
	 */
	public $useSMTP = true;

	/**
	 * SMTP Hostname
	 *
	 * @var string
	 */
	public $smtpHost = 'smtp.sendgrid.net';

	/**
	 * SMTP Secure
	 *
	 * Option can be empty, ssl, or tls
	 *
	 * @var string
	 */
	public $smtpSecure = '';

	/**
	 * SMTP Port
	 *
	 * Typical values are 25, 465 (for ssl) or 587 (for tls)
	 *
	 * @var integer
	 */
	public $smtpPort = 25;

	/**
	 * SMTP Username
	 *
	 * @var string
	 */
	public $smtpUsername = '';

	/**
	 * SMTP Password
	 *
	 * @var string
	 */
	public $smtpPassword = '';

	/**
	 * The Days To Keep Option is used to
	 * tell the clean action how many days
	 * worth of files it is supposed to keep
	 * when it is run.
	 *
	 * @var int
	 */
	public $daysToKeep = 7;
}
